# Generated by Django 2.2.8 on 2019-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Convenience Goods'), (2, 'Shopping Goods'), (3, 'Specialty Goods')], default=1, max_length=125, verbose_name='Category'),
        ),
    ]
